dist: trusty
sudo: required
before_install:
language: python
python:
 - '3.6'
install:
 - pip install .
 - pip install -r requirements-test.txt
script:
 - py.test tests/ --cov deepspectrum  --cov-report term-missing
after_success:
 - coverage combine
 - coveralls
