dist: bionic
sudo: required
before_install:
language: python
python:
 - '3.6'
before_install:
 - sudo apt-get install ffmpeg
install:
 - pip install .
 - pip install -r requirements-test.txt
script:
 - py.test tests/ --cov deepspectrum  --cov-report term
after_success:
 - coveralls
