dist: bionic
sudo: required
language: python
matrix:
  include:
    - name: "Python 3.6 pip"
      python: 
        - "3.6"
      before_install:
      - sudo apt-get install ffmpeg
      install:
      - pip install .
      - pip install -r requirements-test.txt
    - name: "Python 3.7 pip"
      python: 
        - "3.7"
      before_install:
      - sudo apt-get install ffmpeg
      install:
      - pip install .
      - pip install -r requirements-test.txt
    - name: "Anaconda"
      install:
      - sudo apt-get update
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      - bash miniconda.sh -b -p $HOME/miniconda
      - export PATH="$HOME/miniconda/bin:$PATH"
      - hash -r
      - conda config --set always_yes yes --set changeps1 no
      - conda update -q conda
      - conda config --add channels conda-forge
      - conda info -a
      - conda env create -f environment.yml
      - source activate DeepSpectrum
      - conda install --file requirements.txt
script:
 - py.test tests/ --cov deepspectrum  --cov-report term
after_success:
 - coveralls
 