dist: trusty
sudo: required
before_install:
language: python
python:
 - '3.6'
install:
 - pip install .
 - pip install -r requirements-test.txt
script:
 - pytest --cov=deepspectrum tests/
after_success: coveralls
