name: DeepSpectrum
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - click>=7.0
  - imread>=0.7.1
  - librosa >=0.6.3,<0.8.0
  - matplotlib>=3.0.3
  - opencv>=4.1.0
  - numba=0.48.0
  - pillow>=6.0.0
  - tqdm>=4.32.1
  - pytorch>=1.2.0
  - torchvision>=0.5.0
  - pip:
    - tensorflow-gpu>=1.15.2, <2
    - audeep>=0.9.4
    - -e .
