name: DeepSpectrum
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.6.0
  - pip
  - click>=7.0
  - imread>=0.7.1
  - librosa>=0.6.3
  - matplotlib>=3.0.3
  - numpy>=1.16.3
  - opencv>=4.1.0
  - pillow>=6.0.0
  - scipy>=1.2.1
  - tensorflow-gpu >=1.13.0,<2
  - tqdm>=4.32.1
  - pytorch>=1.2.0
  - torchvision>=0.5.0
  - xarray
  - pip:
    - .
