# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pip:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install ffmpeg
      run: sudo apt-get install ffmpeg
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
    - name: Test with pytest
      run: |
        py.test -s tests/ --cov deepspectrum  --cov-report xml:coverage.xml
    - name: Coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml # optional
        fail_ci_if_error: true # optional (default = false)
  conda:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        pythonVersion: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Anaconda-Action
      id: step1
      uses: fdiblen/anaconda-action@0.1.7
      with:
        env-file-name: 'environment.yml'
        channels: conda-forge pytorch
        python-version: 3.7
    - name: Install test dependencies
      run: |
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
    - name: Test with pytest
      run: |
        py.test -s tests/ --cov deepspectrum  --cov-report term
      
